
package com.sdltridion.contentmanager.coreservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import com.sdltridion.contentmanager.r6.ActivityFinishData;
import com.sdltridion.contentmanager.r6.ArrayOfWeakLink;
import com.sdltridion.contentmanager.r6.DeleteTaxonomyNodeMode;
import com.sdltridion.contentmanager.r6.PublishInstructionData;
import com.sdltridion.contentmanager.r6.PublishPriority;
import com.sdltridion.contentmanager.r6.UnPublishInstructionData;
import com.sdltridion.contentmanager.r6.UserData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICoreServiceBatch", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
@XmlSeeAlso({
    com.sdltridion.security.ObjectFactory.class,
    com.sdltridion.contentmanager.coreservice._2012.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.sdltridion.contentmanager.r6.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface ICoreServiceBatch {


    /**
     * 
     * @param userName
     * @return
     *     returns com.sdltridion.contentmanager.r6.UserData
     * @throws ICoreServiceBatchImpersonateBatchCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ImpersonateBatch", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/ImpersonateBatch")
    @WebResult(name = "ImpersonateBatchResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "ImpersonateBatch", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.ImpersonateBatch")
    @ResponseWrapper(localName = "ImpersonateBatchResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.ImpersonateBatchResponse")
    public UserData impersonateBatch(
        @WebParam(name = "userName", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String userName)
        throws ICoreServiceBatchImpersonateBatchCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchLocalizeCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchLocalize", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchLocalize")
    @WebResult(name = "BatchLocalizeResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchLocalize", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchLocalize")
    @ResponseWrapper(localName = "BatchLocalizeResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchLocalizeResponse")
    public String batchLocalize(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks)
        throws ICoreServiceBatchBatchLocalizeCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchUnLocalizeCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchUnLocalize", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchUnLocalize")
    @WebResult(name = "BatchUnLocalizeResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchUnLocalize", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUnLocalize")
    @ResponseWrapper(localName = "BatchUnLocalizeResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUnLocalizeResponse")
    public String batchUnLocalize(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks)
        throws ICoreServiceBatchBatchUnLocalizeCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @param destinationId
     * @param makeUnique
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchCopyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchCopy", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchCopy")
    @WebResult(name = "BatchCopyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchCopy", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCopy")
    @ResponseWrapper(localName = "BatchCopyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCopyResponse")
    public String batchCopy(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "destinationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String destinationId,
        @WebParam(name = "makeUnique", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        Boolean makeUnique)
        throws ICoreServiceBatchBatchCopyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @param destinationId
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchMoveCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchMove", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchMove")
    @WebResult(name = "BatchMoveResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchMove", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchMove")
    @ResponseWrapper(localName = "BatchMoveResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchMoveResponse")
    public String batchMove(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "destinationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String destinationId)
        throws ICoreServiceBatchBatchMoveCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param userComment
     * @param subjectLinks
     * @param removePermanentLock
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchCheckInCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchCheckIn", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchCheckIn")
    @WebResult(name = "BatchCheckInResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchCheckIn", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCheckIn")
    @ResponseWrapper(localName = "BatchCheckInResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCheckInResponse")
    public String batchCheckIn(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "removePermanentLock", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        Boolean removePermanentLock,
        @WebParam(name = "userComment", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String userComment)
        throws ICoreServiceBatchBatchCheckInCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @param permanentLock
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchCheckOutCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchCheckOut", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchCheckOut")
    @WebResult(name = "BatchCheckOutResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchCheckOut", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCheckOut")
    @ResponseWrapper(localName = "BatchCheckOutResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCheckOutResponse")
    public String batchCheckOut(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "permanentLock", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        Boolean permanentLock)
        throws ICoreServiceBatchBatchCheckOutCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchDeleteCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchDelete", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchDelete")
    @WebResult(name = "BatchDeleteResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchDelete", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchDelete")
    @ResponseWrapper(localName = "BatchDeleteResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchDeleteResponse")
    public String batchDelete(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks)
        throws ICoreServiceBatchBatchDeleteCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param priority
     * @param subjectLinks
     * @param publishInstruction
     * @param targets
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchPublishCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchPublish", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchPublish")
    @WebResult(name = "BatchPublishResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchPublish", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchPublish")
    @ResponseWrapper(localName = "BatchPublishResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchPublishResponse")
    public String batchPublish(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "publishInstruction", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        PublishInstructionData publishInstruction,
        @WebParam(name = "targets", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfstring targets,
        @WebParam(name = "priority", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        PublishPriority priority)
        throws ICoreServiceBatchBatchPublishCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param unPublishInstruction
     * @param priority
     * @param subjectLinks
     * @param targets
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchUnPublishCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchUnPublish", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchUnPublish")
    @WebResult(name = "BatchUnPublishResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchUnPublish", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUnPublish")
    @ResponseWrapper(localName = "BatchUnPublishResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUnPublishResponse")
    public String batchUnPublish(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "unPublishInstruction", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        UnPublishInstructionData unPublishInstruction,
        @WebParam(name = "targets", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfstring targets,
        @WebParam(name = "priority", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        PublishPriority priority)
        throws ICoreServiceBatchBatchUnPublishCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @param permanentLock
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchUndoCheckOutCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchUndoCheckOut", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchUndoCheckOut")
    @WebResult(name = "BatchUndoCheckOutResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchUndoCheckOut", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUndoCheckOut")
    @ResponseWrapper(localName = "BatchUndoCheckOutResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUndoCheckOutResponse")
    public String batchUndoCheckOut(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "permanentLock", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        Boolean permanentLock)
        throws ICoreServiceBatchBatchUndoCheckOutCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param activityInstanceLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchStartActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchStartActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchStartActivity")
    @WebResult(name = "BatchStartActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchStartActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchStartActivity")
    @ResponseWrapper(localName = "BatchStartActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchStartActivityResponse")
    public String batchStartActivity(
        @WebParam(name = "activityInstanceLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink activityInstanceLinks)
        throws ICoreServiceBatchBatchStartActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param activityInstanceLinks
     * @param activityFinishData
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchFinishActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchFinishActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchFinishActivity")
    @WebResult(name = "BatchFinishActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchFinishActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchFinishActivity")
    @ResponseWrapper(localName = "BatchFinishActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchFinishActivityResponse")
    public String batchFinishActivity(
        @WebParam(name = "activityInstanceLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink activityInstanceLinks,
        @WebParam(name = "activityFinishData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ActivityFinishData activityFinishData)
        throws ICoreServiceBatchBatchFinishActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param approvalStatusId
     * @param processInstanceLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchForceFinishProcessCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchForceFinishProcess", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchForceFinishProcess")
    @WebResult(name = "BatchForceFinishProcessResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchForceFinishProcess", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchForceFinishProcess")
    @ResponseWrapper(localName = "BatchForceFinishProcessResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchForceFinishProcessResponse")
    public String batchForceFinishProcess(
        @WebParam(name = "processInstanceLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink processInstanceLinks,
        @WebParam(name = "approvalStatusId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String approvalStatusId)
        throws ICoreServiceBatchBatchForceFinishProcessCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param keywordIds
     * @param subjectLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchClassifyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchClassify", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchClassify")
    @WebResult(name = "BatchClassifyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchClassify", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchClassify")
    @ResponseWrapper(localName = "BatchClassifyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchClassifyResponse")
    public String batchClassify(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "keywordIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfstring keywordIds)
        throws ICoreServiceBatchBatchClassifyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param keywordIds
     * @param subjectLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchUnClassifyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchUnClassify", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchUnClassify")
    @WebResult(name = "BatchUnClassifyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchUnClassify", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUnClassify")
    @ResponseWrapper(localName = "BatchUnClassifyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchUnClassifyResponse")
    public String batchUnClassify(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "keywordIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfstring keywordIds)
        throws ICoreServiceBatchBatchUnClassifyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param keywordIdsToAdd
     * @param keywordIdsToRemove
     * @param subjectLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchReClassifyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchReClassify", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchReClassify")
    @WebResult(name = "BatchReClassifyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchReClassify", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchReClassify")
    @ResponseWrapper(localName = "BatchReClassifyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchReClassifyResponse")
    public String batchReClassify(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "keywordIdsToRemove", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfstring keywordIdsToRemove,
        @WebParam(name = "keywordIdsToAdd", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfstring keywordIdsToAdd)
        throws ICoreServiceBatchBatchReClassifyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param deleteTaxonomyNodeMode
     * @param subjectLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchDeleteTaxonomyNodeCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchDeleteTaxonomyNode", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchDeleteTaxonomyNode")
    @WebResult(name = "BatchDeleteTaxonomyNodeResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchDeleteTaxonomyNode", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchDeleteTaxonomyNode")
    @ResponseWrapper(localName = "BatchDeleteTaxonomyNodeResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchDeleteTaxonomyNodeResponse")
    public String batchDeleteTaxonomyNode(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "deleteTaxonomyNodeMode", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        DeleteTaxonomyNodeMode deleteTaxonomyNodeMode)
        throws ICoreServiceBatchBatchDeleteTaxonomyNodeCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @param isEnabled
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchSwitchUserEnabledStateCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchSwitchUserEnabledState", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchSwitchUserEnabledState")
    @WebResult(name = "BatchSwitchUserEnabledStateResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchSwitchUserEnabledState", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchSwitchUserEnabledState")
    @ResponseWrapper(localName = "BatchSwitchUserEnabledStateResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchSwitchUserEnabledStateResponse")
    public String batchSwitchUserEnabledState(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "isEnabled", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        Boolean isEnabled)
        throws ICoreServiceBatchBatchSwitchUserEnabledStateCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @param destinationId
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchCopyToKeywordCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchCopyToKeyword", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchCopyToKeyword")
    @WebResult(name = "BatchCopyToKeywordResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchCopyToKeyword", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCopyToKeyword")
    @ResponseWrapper(localName = "BatchCopyToKeywordResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchCopyToKeywordResponse")
    public String batchCopyToKeyword(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "destinationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String destinationId)
        throws ICoreServiceBatchBatchCopyToKeywordCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectLinks
     * @param destinationId
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchMoveToKeywordCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchMoveToKeyword", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchMoveToKeyword")
    @WebResult(name = "BatchMoveToKeywordResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchMoveToKeyword", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchMoveToKeyword")
    @ResponseWrapper(localName = "BatchMoveToKeywordResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchMoveToKeywordResponse")
    public String batchMoveToKeyword(
        @WebParam(name = "subjectLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink subjectLinks,
        @WebParam(name = "destinationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String destinationId)
        throws ICoreServiceBatchBatchMoveToKeywordCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param activityInstanceLinks
     * @param newAssigneeId
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchReAssignActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchReAssignActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchReAssignActivity")
    @WebResult(name = "BatchReAssignActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchReAssignActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchReAssignActivity")
    @ResponseWrapper(localName = "BatchReAssignActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchReAssignActivityResponse")
    public String batchReAssignActivity(
        @WebParam(name = "activityInstanceLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink activityInstanceLinks,
        @WebParam(name = "newAssigneeId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String newAssigneeId)
        throws ICoreServiceBatchBatchReAssignActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param activityInstanceLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchRestartActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchRestartActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchRestartActivity")
    @WebResult(name = "BatchRestartActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchRestartActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchRestartActivity")
    @ResponseWrapper(localName = "BatchRestartActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchRestartActivityResponse")
    public String batchRestartActivity(
        @WebParam(name = "activityInstanceLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink activityInstanceLinks)
        throws ICoreServiceBatchBatchRestartActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param activityInstanceLinks
     * @param reason
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchSuspendActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchSuspendActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchSuspendActivity")
    @WebResult(name = "BatchSuspendActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchSuspendActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchSuspendActivity")
    @ResponseWrapper(localName = "BatchSuspendActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchSuspendActivityResponse")
    public String batchSuspendActivity(
        @WebParam(name = "activityInstanceLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink activityInstanceLinks,
        @WebParam(name = "reason", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String reason)
        throws ICoreServiceBatchBatchSuspendActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param activityInstanceLinks
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceBatchBatchResumeActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BatchResumeActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/ICoreServiceBatch/BatchResumeActivity")
    @WebResult(name = "BatchResumeActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "BatchResumeActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchResumeActivity")
    @ResponseWrapper(localName = "BatchResumeActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.BatchResumeActivityResponse")
    public String batchResumeActivity(
        @WebParam(name = "activityInstanceLinks", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        ArrayOfWeakLink activityInstanceLinks)
        throws ICoreServiceBatchBatchResumeActivityCoreServiceFaultFaultFaultMessage
    ;

}
