
package com.sdltridion.contentmanager.coreservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import com.sdltridion.contentmanager.r6.ActionFlags;
import com.sdltridion.contentmanager.r6.ActivityFinishData;
import com.sdltridion.contentmanager.r6.ActivityInstanceData;
import com.sdltridion.contentmanager.r6.ApplicationData;
import com.sdltridion.contentmanager.r6.ApplicationDataDictionary;
import com.sdltridion.contentmanager.r6.ArrayOfApplicationData;
import com.sdltridion.contentmanager.r6.ArrayOfIdentifiableObjectData;
import com.sdltridion.contentmanager.r6.ArrayOfPublicationType;
import com.sdltridion.contentmanager.r6.ArrayOfPublishContextData;
import com.sdltridion.contentmanager.r6.ArrayOfPublishInfoData;
import com.sdltridion.contentmanager.r6.ArrayOfPublishTransactionData;
import com.sdltridion.contentmanager.r6.ArrayOfQueueData;
import com.sdltridion.contentmanager.r6.ArrayOfQueueMessageData;
import com.sdltridion.contentmanager.r6.ArrayOfTcmUri;
import com.sdltridion.contentmanager.r6.ArrayOfTemplateType;
import com.sdltridion.contentmanager.r6.ClassificationInfoData;
import com.sdltridion.contentmanager.r6.DeleteTaxonomyNodeMode;
import com.sdltridion.contentmanager.r6.IdentifiableObjectData;
import com.sdltridion.contentmanager.r6.InstanceData;
import com.sdltridion.contentmanager.r6.ItemType;
import com.sdltridion.contentmanager.r6.ProcessHistoryData;
import com.sdltridion.contentmanager.r6.PublishInstructionData;
import com.sdltridion.contentmanager.r6.PublishPriority;
import com.sdltridion.contentmanager.r6.ReadOptions;
import com.sdltridion.contentmanager.r6.RenderedItemData;
import com.sdltridion.contentmanager.r6.RepositoryLocalObjectData;
import com.sdltridion.contentmanager.r6.ResolveInstructionData;
import com.sdltridion.contentmanager.r6.SchemaData;
import com.sdltridion.contentmanager.r6.SchemaFieldsData;
import com.sdltridion.contentmanager.r6.SearchQueryData;
import com.sdltridion.contentmanager.r6.SecurityDescriptorDataDictionary;
import com.sdltridion.contentmanager.r6.SubjectRelatedListFilterData;
import com.sdltridion.contentmanager.r6.SystemWideListFilterData;
import com.sdltridion.contentmanager.r6.UnPublishInstructionData;
import com.sdltridion.contentmanager.r6.UserData;
import com.sdltridion.contentmanager.r6.VersionedItemData;
import com.sdltridion.security.ArrayOfDirectoryServiceUser;
import com.sdltridion.security.ArrayOfWindowsUser;
import com.sdltridion.security.DirectoryUsersFilter;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICoreService", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sdltridion.contentmanager.r6.ObjectFactory.class,
    com.sdltridion.contentmanager.coreservice._2011.ObjectFactory.class,
    com.sdltridion.security.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface ICoreService {


    /**
     * 
     * @param processInstanceId
     * @param approvalStatusId
     * @param readOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.ProcessHistoryData
     * @throws ICoreServiceForceFinishProcessCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ForceFinishProcess", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ForceFinishProcess")
    @WebResult(name = "ForceFinishProcessResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ForceFinishProcess", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ForceFinishProcess")
    @ResponseWrapper(localName = "ForceFinishProcessResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ForceFinishProcessResponse")
    public ProcessHistoryData forceFinishProcess(
        @WebParam(name = "processInstanceId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String processInstanceId,
        @WebParam(name = "approvalStatusId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String approvalStatusId,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceForceFinishProcessCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param queueId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfQueueMessageData
     * @throws ICoreServiceGetListQueueMessagesCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListQueueMessages", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListQueueMessages")
    @WebResult(name = "GetListQueueMessagesResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListQueueMessages", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListQueueMessages")
    @ResponseWrapper(localName = "GetListQueueMessagesResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListQueueMessagesResponse")
    public ArrayOfQueueMessageData getListQueueMessages(
        @WebParam(name = "queueId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Integer queueId)
        throws ICoreServiceGetListQueueMessagesCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfQueueData
     * @throws ICoreServiceGetListQueuesCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListQueues", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListQueues")
    @WebResult(name = "GetListQueuesResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListQueues", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListQueues")
    @ResponseWrapper(localName = "GetListQueuesResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListQueuesResponse")
    public ArrayOfQueueData getListQueues()
        throws ICoreServiceGetListQueuesCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectId
     * @param applicationId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ApplicationData
     * @throws ICoreServiceReadApplicationDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReadApplicationData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ReadApplicationData")
    @WebResult(name = "ReadApplicationDataResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ReadApplicationData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadApplicationData")
    @ResponseWrapper(localName = "ReadApplicationDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadApplicationDataResponse")
    public ApplicationData readApplicationData(
        @WebParam(name = "subjectId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String subjectId,
        @WebParam(name = "applicationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String applicationId)
        throws ICoreServiceReadApplicationDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfApplicationData
     * @throws ICoreServiceReadAllApplicationDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReadAllApplicationData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ReadAllApplicationData")
    @WebResult(name = "ReadAllApplicationDataResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ReadAllApplicationData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadAllApplicationData")
    @ResponseWrapper(localName = "ReadAllApplicationDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadAllApplicationDataResponse")
    public ArrayOfApplicationData readAllApplicationData(
        @WebParam(name = "subjectId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String subjectId)
        throws ICoreServiceReadAllApplicationDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param applicationData
     * @param subjectId
     * @throws ICoreServiceSaveApplicationDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SaveApplicationData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/SaveApplicationData")
    @RequestWrapper(localName = "SaveApplicationData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.SaveApplicationData")
    @ResponseWrapper(localName = "SaveApplicationDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.SaveApplicationDataResponse")
    public void saveApplicationData(
        @WebParam(name = "subjectId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String subjectId,
        @WebParam(name = "applicationData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfApplicationData applicationData)
        throws ICoreServiceSaveApplicationDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectId
     * @param applicationId
     * @throws ICoreServiceDeleteApplicationDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteApplicationData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/DeleteApplicationData")
    @RequestWrapper(localName = "DeleteApplicationData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DeleteApplicationData")
    @ResponseWrapper(localName = "DeleteApplicationDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DeleteApplicationDataResponse")
    public void deleteApplicationData(
        @WebParam(name = "subjectId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String subjectId,
        @WebParam(name = "applicationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String applicationId)
        throws ICoreServiceDeleteApplicationDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws ICoreServiceGetApplicationIdsCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetApplicationIds", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetApplicationIds")
    @WebResult(name = "GetApplicationIdsResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetApplicationIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetApplicationIds")
    @ResponseWrapper(localName = "GetApplicationIdsResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetApplicationIdsResponse")
    public ArrayOfstring getApplicationIds()
        throws ICoreServiceGetApplicationIdsCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param applicationId
     * @throws ICoreServicePurgeApplicationDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "PurgeApplicationData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/PurgeApplicationData")
    @RequestWrapper(localName = "PurgeApplicationData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.PurgeApplicationData")
    @ResponseWrapper(localName = "PurgeApplicationDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.PurgeApplicationDataResponse")
    public void purgeApplicationData(
        @WebParam(name = "applicationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String applicationId)
        throws ICoreServicePurgeApplicationDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param resolveInstruction
     * @param ids
     * @param readOptions
     * @param targets
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfPublishContextData
     * @throws ICoreServiceResolveItemsCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ResolveItems", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ResolveItems")
    @WebResult(name = "ResolveItemsResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ResolveItems", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ResolveItems")
    @ResponseWrapper(localName = "ResolveItemsResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ResolveItemsResponse")
    public ArrayOfPublishContextData resolveItems(
        @WebParam(name = "ids", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring ids,
        @WebParam(name = "resolveInstruction", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ResolveInstructionData resolveInstruction,
        @WebParam(name = "targets", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring targets,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceResolveItemsCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXmlResponse.GetSearchResultsXmlResult
     * @throws ICoreServiceGetSearchResultsXmlCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSearchResultsXml", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSearchResultsXml")
    @WebResult(name = "GetSearchResultsXmlResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSearchResultsXml", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXml")
    @ResponseWrapper(localName = "GetSearchResultsXmlResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXmlResponse")
    public com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXmlResponse.GetSearchResultsXmlResult getSearchResultsXml(
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SearchQueryData filter)
        throws ICoreServiceGetSearchResultsXmlCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param startRowIndex
     * @param maxRows
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXmlPagedResponse.GetSearchResultsXmlPagedResult
     * @throws ICoreServiceGetSearchResultsXmlPagedCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSearchResultsXmlPaged", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSearchResultsXmlPaged")
    @WebResult(name = "GetSearchResultsXmlPagedResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSearchResultsXmlPaged", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXmlPaged")
    @ResponseWrapper(localName = "GetSearchResultsXmlPagedResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXmlPagedResponse")
    public com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsXmlPagedResponse.GetSearchResultsXmlPagedResult getSearchResultsXmlPaged(
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SearchQueryData filter,
        @WebParam(name = "startRowIndex", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Integer startRowIndex,
        @WebParam(name = "maxRows", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Integer maxRows)
        throws ICoreServiceGetSearchResultsXmlPagedCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfIdentifiableObjectData
     * @throws ICoreServiceGetSearchResultsCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSearchResults", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSearchResults")
    @WebResult(name = "GetSearchResultsResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSearchResults", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResults")
    @ResponseWrapper(localName = "GetSearchResultsResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsResponse")
    public ArrayOfIdentifiableObjectData getSearchResults(
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SearchQueryData filter)
        throws ICoreServiceGetSearchResultsCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param startRowIndex
     * @param maxRows
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfIdentifiableObjectData
     * @throws ICoreServiceGetSearchResultsPagedCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSearchResultsPaged", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSearchResultsPaged")
    @WebResult(name = "GetSearchResultsPagedResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSearchResultsPaged", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsPaged")
    @ResponseWrapper(localName = "GetSearchResultsPagedResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSearchResultsPagedResponse")
    public ArrayOfIdentifiableObjectData getSearchResultsPaged(
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SearchQueryData filter,
        @WebParam(name = "startRowIndex", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Integer startRowIndex,
        @WebParam(name = "maxRows", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Integer maxRows)
        throws ICoreServiceGetSearchResultsPagedCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param templateId
     * @param publicationTargetId
     * @param publishInstruction
     * @param itemId
     * @return
     *     returns com.sdltridion.contentmanager.r6.RenderedItemData
     * @throws ICoreServiceRenderItemCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RenderItem", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/RenderItem")
    @WebResult(name = "RenderItemResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "RenderItem", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.RenderItem")
    @ResponseWrapper(localName = "RenderItemResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.RenderItemResponse")
    public RenderedItemData renderItem(
        @WebParam(name = "itemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String itemId,
        @WebParam(name = "templateId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String templateId,
        @WebParam(name = "publishInstruction", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        PublishInstructionData publishInstruction,
        @WebParam(name = "publicationTargetId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String publicationTargetId)
        throws ICoreServiceRenderItemCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param priority
     * @param ids
     * @param readOptions
     * @param publishInstruction
     * @param targets
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfPublishTransactionData
     * @throws ICoreServicePublishCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Publish", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Publish")
    @WebResult(name = "PublishResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Publish", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Publish")
    @ResponseWrapper(localName = "PublishResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.PublishResponse")
    public ArrayOfPublishTransactionData publish(
        @WebParam(name = "ids", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring ids,
        @WebParam(name = "publishInstruction", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        PublishInstructionData publishInstruction,
        @WebParam(name = "targets", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring targets,
        @WebParam(name = "priority", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        PublishPriority priority,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServicePublishCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param unPublishInstruction
     * @param priority
     * @param ids
     * @param readOptions
     * @param targets
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfPublishTransactionData
     * @throws ICoreServiceUnPublishCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnPublish", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/UnPublish")
    @WebResult(name = "UnPublishResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "UnPublish", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UnPublish")
    @ResponseWrapper(localName = "UnPublishResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UnPublishResponse")
    public ArrayOfPublishTransactionData unPublish(
        @WebParam(name = "ids", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring ids,
        @WebParam(name = "unPublishInstruction", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        UnPublishInstructionData unPublishInstruction,
        @WebParam(name = "targets", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring targets,
        @WebParam(name = "priority", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        PublishPriority priority,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceUnPublishCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param isPublishedInContext
     * @param publicationTargetId
     * @param itemId
     * @return
     *     returns java.lang.Boolean
     * @throws ICoreServiceIsPublishedCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "IsPublished", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/IsPublished")
    @WebResult(name = "IsPublishedResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "IsPublished", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.IsPublished")
    @ResponseWrapper(localName = "IsPublishedResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.IsPublishedResponse")
    public Boolean isPublished(
        @WebParam(name = "itemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String itemId,
        @WebParam(name = "publicationTargetId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String publicationTargetId,
        @WebParam(name = "isPublishedInContext", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Boolean isPublishedInContext)
        throws ICoreServiceIsPublishedCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param workItemId
     * @return
     *     returns com.sdltridion.contentmanager.r6.RenderedItemData
     * @throws ICoreServiceGetWorkItemSnapshotCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetWorkItemSnapshot", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetWorkItemSnapshot")
    @WebResult(name = "GetWorkItemSnapshotResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetWorkItemSnapshot", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetWorkItemSnapshot")
    @ResponseWrapper(localName = "GetWorkItemSnapshotResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetWorkItemSnapshotResponse")
    public RenderedItemData getWorkItemSnapshot(
        @WebParam(name = "workItemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String workItemId)
        throws ICoreServiceGetWorkItemSnapshotCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param itemId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfPublishInfoData
     * @throws ICoreServiceGetListPublishInfoCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListPublishInfo", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListPublishInfo")
    @WebResult(name = "GetListPublishInfoResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListPublishInfo", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListPublishInfo")
    @ResponseWrapper(localName = "GetListPublishInfoResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListPublishInfoResponse")
    public ArrayOfPublishInfoData getListPublishInfo(
        @WebParam(name = "itemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String itemId)
        throws ICoreServiceGetListPublishInfoCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param numericActions
     * @return
     *     returns com.sdltridion.contentmanager.r6.ActionFlags
     * @throws ICoreServiceCastActionsCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CastActions", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/CastActions")
    @WebResult(name = "CastActionsResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "CastActions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CastActions")
    @ResponseWrapper(localName = "CastActionsResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CastActionsResponse")
    public ActionFlags castActions(
        @WebParam(name = "numericActions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Integer numericActions)
        throws ICoreServiceCastActionsCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param data
     * @throws ICoreServiceValidateXmlCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ValidateXml", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ValidateXml")
    @RequestWrapper(localName = "ValidateXml", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ValidateXml")
    @ResponseWrapper(localName = "ValidateXmlResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ValidateXmlResponse")
    public void validateXml(
        @WebParam(name = "data", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        IdentifiableObjectData data)
        throws ICoreServiceValidateXmlCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param data
     * @return
     *     returns java.lang.Boolean
     * @throws ICoreServiceIsValidTridionWebSchemaXmlCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "IsValidTridionWebSchemaXml", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/IsValidTridionWebSchemaXml")
    @WebResult(name = "IsValidTridionWebSchemaXmlResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "IsValidTridionWebSchemaXml", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.IsValidTridionWebSchemaXml")
    @ResponseWrapper(localName = "IsValidTridionWebSchemaXmlResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.IsValidTridionWebSchemaXmlResponse")
    public Boolean isValidTridionWebSchemaXml(
        @WebParam(name = "data", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SchemaData data)
        throws ICoreServiceIsValidTridionWebSchemaXmlCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param applicationId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfTcmUri
     * @throws ICoreServiceGetSubjectIdsWithApplicationDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSubjectIdsWithApplicationData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSubjectIdsWithApplicationData")
    @WebResult(name = "GetSubjectIdsWithApplicationDataResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSubjectIdsWithApplicationData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSubjectIdsWithApplicationData")
    @ResponseWrapper(localName = "GetSubjectIdsWithApplicationDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSubjectIdsWithApplicationDataResponse")
    public ArrayOfTcmUri getSubjectIdsWithApplicationData(
        @WebParam(name = "applicationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String applicationId)
        throws ICoreServiceGetSubjectIdsWithApplicationDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectIds
     * @param applicationIds
     * @return
     *     returns com.sdltridion.contentmanager.r6.ApplicationDataDictionary
     * @throws ICoreServiceReadApplicationDataForSubjectsIdsCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReadApplicationDataForSubjectsIds", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ReadApplicationDataForSubjectsIds")
    @WebResult(name = "ReadApplicationDataForSubjectsIdsResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ReadApplicationDataForSubjectsIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadApplicationDataForSubjectsIds")
    @ResponseWrapper(localName = "ReadApplicationDataForSubjectsIdsResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadApplicationDataForSubjectsIdsResponse")
    public ApplicationDataDictionary readApplicationDataForSubjectsIds(
        @WebParam(name = "subjectIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring subjectIds,
        @WebParam(name = "applicationIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring applicationIds)
        throws ICoreServiceReadApplicationDataForSubjectsIdsCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param subjectIds
     * @return
     *     returns com.sdltridion.contentmanager.r6.SecurityDescriptorDataDictionary
     * @throws ICoreServiceGetSecurityDescriptorsForSubjectsIdsCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSecurityDescriptorsForSubjectsIds", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSecurityDescriptorsForSubjectsIds")
    @WebResult(name = "GetSecurityDescriptorsForSubjectsIdsResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSecurityDescriptorsForSubjectsIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSecurityDescriptorsForSubjectsIds")
    @ResponseWrapper(localName = "GetSecurityDescriptorsForSubjectsIdsResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSecurityDescriptorsForSubjectsIdsResponse")
    public SecurityDescriptorDataDictionary getSecurityDescriptorsForSubjectsIds(
        @WebParam(name = "subjectIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring subjectIds)
        throws ICoreServiceGetSecurityDescriptorsForSubjectsIdsCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceGetApiVersionCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetApiVersion", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetApiVersion")
    @WebResult(name = "GetApiVersionResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetApiVersion", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetApiVersion")
    @ResponseWrapper(localName = "GetApiVersionResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetApiVersionResponse")
    public String getApiVersion()
        throws ICoreServiceGetApiVersionCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.sdltridion.contentmanager.r6.UserData
     * @throws ICoreServiceGetCurrentUserCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCurrentUser", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetCurrentUser")
    @WebResult(name = "GetCurrentUserResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetCurrentUser", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetCurrentUser")
    @ResponseWrapper(localName = "GetCurrentUserResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetCurrentUserResponse")
    public UserData getCurrentUser()
        throws ICoreServiceGetCurrentUserCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     * @throws ICoreServiceIsExistingObjectCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "IsExistingObject", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/IsExistingObject")
    @WebResult(name = "IsExistingObjectResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "IsExistingObject", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.IsExistingObject")
    @ResponseWrapper(localName = "IsExistingObjectResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.IsExistingObjectResponse")
    public Boolean isExistingObject(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id)
        throws ICoreServiceIsExistingObjectCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param contextRepositoryUri
     * @param baseUri
     * @param version
     * @return
     *     returns java.lang.String
     * @throws ICoreServiceGetTcmUriCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetTcmUri", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetTcmUri")
    @WebResult(name = "GetTcmUriResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetTcmUri", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetTcmUri")
    @ResponseWrapper(localName = "GetTcmUriResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetTcmUriResponse")
    public String getTcmUri(
        @WebParam(name = "baseUri", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String baseUri,
        @WebParam(name = "contextRepositoryUri", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String contextRepositoryUri,
        @WebParam(name = "version", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Long version)
        throws ICoreServiceGetTcmUriCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.IdentifiableObjectData
     * @throws ICoreServiceReadCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Read", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Read")
    @WebResult(name = "ReadResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Read", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Read")
    @ResponseWrapper(localName = "ReadResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadResponse")
    public IdentifiableObjectData read(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceReadCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param expandEmbeddedFields
     * @param readOptions
     * @param schemaId
     * @return
     *     returns com.sdltridion.contentmanager.r6.SchemaFieldsData
     * @throws ICoreServiceReadSchemaFieldsCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReadSchemaFields", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ReadSchemaFields")
    @WebResult(name = "ReadSchemaFieldsResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ReadSchemaFields", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadSchemaFields")
    @ResponseWrapper(localName = "ReadSchemaFieldsResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReadSchemaFieldsResponse")
    public SchemaFieldsData readSchemaFields(
        @WebParam(name = "schemaId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String schemaId,
        @WebParam(name = "expandEmbeddedFields", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Boolean expandEmbeddedFields,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceReadSchemaFieldsCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param schemaFieldsData
     * @return
     *     returns com.sdltridion.contentmanager.coreservice._2011.ConvertSchemaFieldsToXsdResponse.ConvertSchemaFieldsToXsdResult
     * @throws ICoreServiceConvertSchemaFieldsToXsdCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ConvertSchemaFieldsToXsd", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ConvertSchemaFieldsToXsd")
    @WebResult(name = "ConvertSchemaFieldsToXsdResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ConvertSchemaFieldsToXsd", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ConvertSchemaFieldsToXsd")
    @ResponseWrapper(localName = "ConvertSchemaFieldsToXsdResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ConvertSchemaFieldsToXsdResponse")
    public com.sdltridion.contentmanager.coreservice._2011.ConvertSchemaFieldsToXsdResponse.ConvertSchemaFieldsToXsdResult convertSchemaFieldsToXsd(
        @WebParam(name = "schemaFieldsData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SchemaFieldsData schemaFieldsData)
        throws ICoreServiceConvertSchemaFieldsToXsdCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readBackOptions
     * @param deltaData
     * @return
     *     returns com.sdltridion.contentmanager.r6.IdentifiableObjectData
     * @throws ICoreServiceSaveCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Save", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Save")
    @WebResult(name = "SaveResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Save", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Save")
    @ResponseWrapper(localName = "SaveResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.SaveResponse")
    public IdentifiableObjectData save(
        @WebParam(name = "deltaData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        IdentifiableObjectData deltaData,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceSaveCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @throws ICoreServiceDeleteCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Delete", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Delete")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DeleteResponse")
    public void delete(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id)
        throws ICoreServiceDeleteCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param deleteTaxonomyNodeMode
     * @throws ICoreServiceDeleteTaxonomyNodeCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteTaxonomyNode", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/DeleteTaxonomyNode")
    @RequestWrapper(localName = "DeleteTaxonomyNode", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DeleteTaxonomyNode")
    @ResponseWrapper(localName = "DeleteTaxonomyNodeResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DeleteTaxonomyNodeResponse")
    public void deleteTaxonomyNode(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "deleteTaxonomyNodeMode", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        DeleteTaxonomyNodeMode deleteTaxonomyNodeMode)
        throws ICoreServiceDeleteTaxonomyNodeCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param itemType
     * @param containerId
     * @return
     *     returns com.sdltridion.contentmanager.r6.IdentifiableObjectData
     * @throws ICoreServiceGetDefaultDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDefaultData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetDefaultData")
    @WebResult(name = "GetDefaultDataResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetDefaultData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetDefaultData")
    @ResponseWrapper(localName = "GetDefaultDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetDefaultDataResponse")
    public IdentifiableObjectData getDefaultData(
        @WebParam(name = "itemType", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ItemType itemType,
        @WebParam(name = "containerId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String containerId)
        throws ICoreServiceGetDefaultDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @param destinationId
     * @return
     *     returns com.sdltridion.contentmanager.r6.RepositoryLocalObjectData
     * @throws ICoreServiceMoveCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Move", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Move")
    @WebResult(name = "MoveResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Move", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Move")
    @ResponseWrapper(localName = "MoveResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.MoveResponse")
    public RepositoryLocalObjectData move(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "destinationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String destinationId,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceMoveCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @param destinationId
     * @param makeUnique
     * @return
     *     returns com.sdltridion.contentmanager.r6.RepositoryLocalObjectData
     * @throws ICoreServiceCopyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Copy", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Copy")
    @WebResult(name = "CopyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Copy", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Copy")
    @ResponseWrapper(localName = "CopyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CopyResponse")
    public RepositoryLocalObjectData copy(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "destinationId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String destinationId,
        @WebParam(name = "makeUnique", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Boolean makeUnique,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceCopyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readOptions
     * @param schemaId
     * @param containerItemId
     * @return
     *     returns com.sdltridion.contentmanager.r6.InstanceData
     * @throws ICoreServiceGetInstanceDataCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetInstanceData", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetInstanceData")
    @WebResult(name = "GetInstanceDataResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetInstanceData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetInstanceData")
    @ResponseWrapper(localName = "GetInstanceDataResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetInstanceDataResponse")
    public InstanceData getInstanceData(
        @WebParam(name = "schemaId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String schemaId,
        @WebParam(name = "containerItemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String containerItemId,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceGetInstanceDataCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.IdentifiableObjectData
     * @throws ICoreServiceTryCheckOutCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "TryCheckOut", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/TryCheckOut")
    @WebResult(name = "TryCheckOutResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "TryCheckOut", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.TryCheckOut")
    @ResponseWrapper(localName = "TryCheckOutResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.TryCheckOutResponse")
    public IdentifiableObjectData tryCheckOut(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceTryCheckOutCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @param permanentLock
     * @return
     *     returns com.sdltridion.contentmanager.r6.VersionedItemData
     * @throws ICoreServiceCheckOutCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CheckOut", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/CheckOut")
    @WebResult(name = "CheckOutResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "CheckOut", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CheckOut")
    @ResponseWrapper(localName = "CheckOutResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CheckOutResponse")
    public VersionedItemData checkOut(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "permanentLock", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Boolean permanentLock,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceCheckOutCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.VersionedItemData
     * @throws ICoreServiceCheckInCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CheckIn", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/CheckIn")
    @WebResult(name = "CheckInResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "CheckIn", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CheckIn")
    @ResponseWrapper(localName = "CheckInResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CheckInResponse")
    public VersionedItemData checkIn(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceCheckInCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readBackOptions
     * @param deltaData
     * @return
     *     returns com.sdltridion.contentmanager.r6.IdentifiableObjectData
     * @throws ICoreServiceUpdateCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Update", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Update")
    @WebResult(name = "UpdateResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Update", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UpdateResponse")
    public IdentifiableObjectData update(
        @WebParam(name = "deltaData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        IdentifiableObjectData deltaData,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceUpdateCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readBackOptions
     * @param data
     * @return
     *     returns com.sdltridion.contentmanager.r6.IdentifiableObjectData
     * @throws ICoreServiceCreateCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Create", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Create")
    @WebResult(name = "CreateResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Create", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.CreateResponse")
    public IdentifiableObjectData create(
        @WebParam(name = "data", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        IdentifiableObjectData data,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceCreateCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @param permanentLock
     * @return
     *     returns com.sdltridion.contentmanager.r6.VersionedItemData
     * @throws ICoreServiceUndoCheckOutCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UndoCheckOut", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/UndoCheckOut")
    @WebResult(name = "UndoCheckOutResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "UndoCheckOut", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UndoCheckOut")
    @ResponseWrapper(localName = "UndoCheckOutResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UndoCheckOutResponse")
    public VersionedItemData undoCheckOut(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "permanentLock", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Boolean permanentLock,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceUndoCheckOutCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @param deleteVersions
     * @param comment
     * @return
     *     returns com.sdltridion.contentmanager.r6.VersionedItemData
     * @throws ICoreServiceRollbackCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Rollback", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Rollback")
    @WebResult(name = "RollbackResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Rollback", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Rollback")
    @ResponseWrapper(localName = "RollbackResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.RollbackResponse")
    public VersionedItemData rollback(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "deleteVersions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        Boolean deleteVersions,
        @WebParam(name = "comment", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String comment,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceRollbackCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.RepositoryLocalObjectData
     * @throws ICoreServiceLocalizeCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Localize", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Localize")
    @WebResult(name = "LocalizeResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Localize", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Localize")
    @ResponseWrapper(localName = "LocalizeResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.LocalizeResponse")
    public RepositoryLocalObjectData localize(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceLocalizeCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param readBackOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.RepositoryLocalObjectData
     * @throws ICoreServiceUnLocalizeCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnLocalize", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/UnLocalize")
    @WebResult(name = "UnLocalizeResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "UnLocalize", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UnLocalize")
    @ResponseWrapper(localName = "UnLocalizeResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UnLocalizeResponse")
    public RepositoryLocalObjectData unLocalize(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceUnLocalizeCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param itemType
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfTemplateType
     * @throws ICoreServiceGetListTemplateTypesCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListTemplateTypes", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListTemplateTypes")
    @WebResult(name = "GetListTemplateTypesResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListTemplateTypes", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListTemplateTypes")
    @ResponseWrapper(localName = "GetListTemplateTypesResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListTemplateTypesResponse")
    public ArrayOfTemplateType getListTemplateTypes(
        @WebParam(name = "itemType", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ItemType itemType)
        throws ICoreServiceGetListTemplateTypesCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfPublicationType
     * @throws ICoreServiceGetListPublicationTypesCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListPublicationTypes", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListPublicationTypes")
    @WebResult(name = "GetListPublicationTypesResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListPublicationTypes", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListPublicationTypes")
    @ResponseWrapper(localName = "GetListPublicationTypesResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListPublicationTypesResponse")
    public ArrayOfPublicationType getListPublicationTypes()
        throws ICoreServiceGetListPublicationTypesCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.coreservice._2011.GetSystemWideListXmlResponse.GetSystemWideListXmlResult
     * @throws ICoreServiceGetSystemWideListXmlCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSystemWideListXml", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSystemWideListXml")
    @WebResult(name = "GetSystemWideListXmlResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSystemWideListXml", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSystemWideListXml")
    @ResponseWrapper(localName = "GetSystemWideListXmlResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSystemWideListXmlResponse")
    public com.sdltridion.contentmanager.coreservice._2011.GetSystemWideListXmlResponse.GetSystemWideListXmlResult getSystemWideListXml(
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SystemWideListFilterData filter)
        throws ICoreServiceGetSystemWideListXmlCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfIdentifiableObjectData
     * @throws ICoreServiceGetSystemWideListCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSystemWideList", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetSystemWideList")
    @WebResult(name = "GetSystemWideListResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetSystemWideList", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSystemWideList")
    @ResponseWrapper(localName = "GetSystemWideListResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetSystemWideListResponse")
    public ArrayOfIdentifiableObjectData getSystemWideList(
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SystemWideListFilterData filter)
        throws ICoreServiceGetSystemWideListCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.coreservice._2011.GetListXmlResponse.GetListXmlResult
     * @throws ICoreServiceGetListXmlCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListXml", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListXml")
    @WebResult(name = "GetListXmlResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListXml", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListXml")
    @ResponseWrapper(localName = "GetListXmlResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListXmlResponse")
    public com.sdltridion.contentmanager.coreservice._2011.GetListXmlResponse.GetListXmlResult getListXml(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SubjectRelatedListFilterData filter)
        throws ICoreServiceGetListXmlCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param filter
     * @return
     *     returns com.sdltridion.contentmanager.r6.ArrayOfIdentifiableObjectData
     * @throws ICoreServiceGetListCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetList", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetList")
    @WebResult(name = "GetListResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetList", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListResponse")
    public ArrayOfIdentifiableObjectData getList(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        SubjectRelatedListFilterData filter)
        throws ICoreServiceGetListCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     * @throws ICoreServiceGetListDirectoryServiceNamesCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListDirectoryServiceNames", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListDirectoryServiceNames")
    @WebResult(name = "GetListDirectoryServiceNamesResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListDirectoryServiceNames", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceNames")
    @ResponseWrapper(localName = "GetListDirectoryServiceNamesResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceNamesResponse")
    public ArrayOfstring getListDirectoryServiceNames()
        throws ICoreServiceGetListDirectoryServiceNamesCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param domainName
     * @return
     *     returns com.sdltridion.security.ArrayOfWindowsUser
     * @throws ICoreServiceGetListWindowsDomainUsersCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListWindowsDomainUsers", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListWindowsDomainUsers")
    @WebResult(name = "GetListWindowsDomainUsersResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListWindowsDomainUsers", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListWindowsDomainUsers")
    @ResponseWrapper(localName = "GetListWindowsDomainUsersResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListWindowsDomainUsersResponse")
    public ArrayOfWindowsUser getListWindowsDomainUsers(
        @WebParam(name = "domainName", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String domainName)
        throws ICoreServiceGetListWindowsDomainUsersCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param directoryServiceName
     * @return
     *     returns com.sdltridion.security.ArrayOfDirectoryServiceUser
     * @throws ICoreServiceGetListDirectoryServiceAllUsersCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListDirectoryServiceAllUsers", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListDirectoryServiceAllUsers")
    @WebResult(name = "GetListDirectoryServiceAllUsersResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListDirectoryServiceAllUsers", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceAllUsers")
    @ResponseWrapper(localName = "GetListDirectoryServiceAllUsersResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceAllUsersResponse")
    public ArrayOfDirectoryServiceUser getListDirectoryServiceAllUsers(
        @WebParam(name = "directoryServiceName", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String directoryServiceName)
        throws ICoreServiceGetListDirectoryServiceAllUsersCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param groupDN
     * @param directoryServiceName
     * @return
     *     returns com.sdltridion.security.ArrayOfDirectoryServiceUser
     * @throws ICoreServiceGetListDirectoryServiceGroupMembersCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListDirectoryServiceGroupMembers", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListDirectoryServiceGroupMembers")
    @WebResult(name = "GetListDirectoryServiceGroupMembersResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListDirectoryServiceGroupMembers", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceGroupMembers")
    @ResponseWrapper(localName = "GetListDirectoryServiceGroupMembersResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceGroupMembersResponse")
    public ArrayOfDirectoryServiceUser getListDirectoryServiceGroupMembers(
        @WebParam(name = "directoryServiceName", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String directoryServiceName,
        @WebParam(name = "groupDN", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String groupDN)
        throws ICoreServiceGetListDirectoryServiceGroupMembersCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param directoryServiceName
     * @return
     *     returns com.sdltridion.security.ArrayOfDirectoryServiceUser
     * @throws ICoreServiceGetListDirectoryServiceUsersCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetListDirectoryServiceUsers", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/GetListDirectoryServiceUsers")
    @WebResult(name = "GetListDirectoryServiceUsersResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "GetListDirectoryServiceUsers", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceUsers")
    @ResponseWrapper(localName = "GetListDirectoryServiceUsersResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.GetListDirectoryServiceUsersResponse")
    public ArrayOfDirectoryServiceUser getListDirectoryServiceUsers(
        @WebParam(name = "directoryServiceName", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String directoryServiceName,
        @WebParam(name = "filter", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        DirectoryUsersFilter filter)
        throws ICoreServiceGetListDirectoryServiceUsersCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param keywordIds
     * @param id
     * @param readOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.ClassificationInfoData
     * @throws ICoreServiceClassifyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Classify", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/Classify")
    @WebResult(name = "ClassifyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "Classify", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.Classify")
    @ResponseWrapper(localName = "ClassifyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ClassifyResponse")
    public ClassificationInfoData classify(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "keywordIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring keywordIds,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceClassifyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param keywordIds
     * @param id
     * @param readOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.ClassificationInfoData
     * @throws ICoreServiceUnClassifyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnClassify", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/UnClassify")
    @WebResult(name = "UnClassifyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "UnClassify", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UnClassify")
    @ResponseWrapper(localName = "UnClassifyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UnClassifyResponse")
    public ClassificationInfoData unClassify(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "keywordIds", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring keywordIds,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceUnClassifyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param keywordIdsToAdd
     * @param keywordIdsToRemove
     * @param readOptions
     * @return
     *     returns com.sdltridion.contentmanager.r6.ClassificationInfoData
     * @throws ICoreServiceReClassifyCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReClassify", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ReClassify")
    @WebResult(name = "ReClassifyResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ReClassify", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReClassify")
    @ResponseWrapper(localName = "ReClassifyResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReClassifyResponse")
    public ClassificationInfoData reClassify(
        @WebParam(name = "id", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String id,
        @WebParam(name = "keywordIdsToRemove", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring keywordIdsToRemove,
        @WebParam(name = "keywordIdsToAdd", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ArrayOfstring keywordIdsToAdd,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceReClassifyCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readBackOptions
     * @param activityInstanceId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ActivityInstanceData
     * @throws ICoreServiceStartActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/StartActivity")
    @WebResult(name = "StartActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "StartActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.StartActivity")
    @ResponseWrapper(localName = "StartActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.StartActivityResponse")
    public ActivityInstanceData startActivity(
        @WebParam(name = "activityInstanceId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String activityInstanceId,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceStartActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readBackOptions
     * @param activityInstanceId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ActivityInstanceData
     * @throws ICoreServiceSuspendActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SuspendActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/SuspendActivity")
    @WebResult(name = "SuspendActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "SuspendActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.SuspendActivity")
    @ResponseWrapper(localName = "SuspendActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.SuspendActivityResponse")
    public ActivityInstanceData suspendActivity(
        @WebParam(name = "activityInstanceId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String activityInstanceId,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceSuspendActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readBackOptions
     * @param activityInstanceId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ActivityInstanceData
     * @throws ICoreServiceRestartActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RestartActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/RestartActivity")
    @WebResult(name = "RestartActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "RestartActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.RestartActivity")
    @ResponseWrapper(localName = "RestartActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.RestartActivityResponse")
    public ActivityInstanceData restartActivity(
        @WebParam(name = "activityInstanceId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String activityInstanceId,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceRestartActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readBackOptions
     * @param newAssigneeId
     * @param activityInstanceId
     * @return
     *     returns com.sdltridion.contentmanager.r6.ActivityInstanceData
     * @throws ICoreServiceReAssignActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReAssignActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/ReAssignActivity")
    @WebResult(name = "ReAssignActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "ReAssignActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReAssignActivity")
    @ResponseWrapper(localName = "ReAssignActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.ReAssignActivityResponse")
    public ActivityInstanceData reAssignActivity(
        @WebParam(name = "activityInstanceId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String activityInstanceId,
        @WebParam(name = "newAssigneeId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String newAssigneeId,
        @WebParam(name = "readBackOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readBackOptions)
        throws ICoreServiceReAssignActivityCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param readOptions
     * @param activityInstanceId
     * @param activityFinishData
     * @return
     *     returns com.sdltridion.contentmanager.r6.ActivityInstanceData
     * @throws ICoreServiceFinishActivityCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "FinishActivity", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/ICoreService/FinishActivity")
    @WebResult(name = "FinishActivityResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "FinishActivity", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.FinishActivity")
    @ResponseWrapper(localName = "FinishActivityResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.FinishActivityResponse")
    public ActivityInstanceData finishActivity(
        @WebParam(name = "activityInstanceId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String activityInstanceId,
        @WebParam(name = "activityFinishData", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ActivityFinishData activityFinishData,
        @WebParam(name = "readOptions", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        ReadOptions readOptions)
        throws ICoreServiceFinishActivityCoreServiceFaultFaultFaultMessage
    ;

}
