
package com.sdltridion.contentmanager.coreservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.sdltridion.contentmanager.r6.UserData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IStreamDownload", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
@XmlSeeAlso({
    com.sdltridion.security.ObjectFactory.class,
    com.sdltridion.contentmanager.coreservice._2012.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.sdltridion.contentmanager.r6.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface IStreamDownload {


    /**
     * 
     * @param itemId
     * @return
     *     returns byte[]
     * @throws IStreamDownloadDownloadBinaryContentCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadBinaryContent", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/IStreamDownload/DownloadBinaryContent")
    @WebResult(name = "DownloadBinaryContentResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "DownloadBinaryContent", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.DownloadBinaryContent")
    @ResponseWrapper(localName = "DownloadBinaryContentResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.DownloadBinaryContentResponse")
    public byte[] downloadBinaryContent(
        @WebParam(name = "itemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String itemId)
        throws IStreamDownloadDownloadBinaryContentCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accessToken
     * @param itemId
     * @return
     *     returns byte[]
     * @throws IStreamDownloadDownloadBinaryContentByUserCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadBinaryContentByUser", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/IStreamDownload/DownloadBinaryContentByUser")
    @WebResult(name = "DownloadBinaryContentByUserResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "DownloadBinaryContentByUser", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.DownloadBinaryContentByUser")
    @ResponseWrapper(localName = "DownloadBinaryContentByUserResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.DownloadBinaryContentByUserResponse")
    public byte[] downloadBinaryContentByUser(
        @WebParam(name = "itemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String itemId,
        @WebParam(name = "accessToken", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        UserData accessToken)
        throws IStreamDownloadDownloadBinaryContentByUserCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param path
     * @return
     *     returns byte[]
     * @throws IStreamDownloadDownloadRenderedBinaryCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadRenderedBinary", action = "http://www.sdltridion.com/ContentManager/CoreService/2012/IStreamDownload/DownloadRenderedBinary")
    @WebResult(name = "DownloadRenderedBinaryResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
    @RequestWrapper(localName = "DownloadRenderedBinary", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.DownloadRenderedBinary")
    @ResponseWrapper(localName = "DownloadRenderedBinaryResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012", className = "com.sdltridion.contentmanager.coreservice._2012.DownloadRenderedBinaryResponse")
    public byte[] downloadRenderedBinary(
        @WebParam(name = "path", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2012")
        String path)
        throws IStreamDownloadDownloadRenderedBinaryCoreServiceFaultFaultFaultMessage
    ;

}
