
package com.sdltridion.contentmanager.coreservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.sdltridion.contentmanager.coreservice._2011.UploadRequest;
import com.sdltridion.contentmanager.coreservice._2011.UploadResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IStreamUpload", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sdltridion.contentmanager.r6.ObjectFactory.class,
    com.sdltridion.contentmanager.coreservice._2011.ObjectFactory.class,
    com.sdltridion.security.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface IStreamUpload {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sdltridion.contentmanager.coreservice._2011.UploadResponse
     * @throws IStreamUploadUploadBinaryContentCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UploadBinaryContent", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/IStreamUpload/UploadBinaryContent")
    @WebResult(name = "UploadResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UploadResponse uploadBinaryContent(
        @WebParam(name = "UploadRequest", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", partName = "parameters")
        UploadRequest parameters)
        throws IStreamUploadUploadBinaryContentCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param data
     * @param fileName
     * @return
     *     returns java.lang.String
     * @throws IStreamUploadUploadBinaryByteArrayCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UploadBinaryByteArray", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/IStreamUpload/UploadBinaryByteArray")
    @WebResult(name = "UploadBinaryByteArrayResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "UploadBinaryByteArray", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UploadBinaryByteArray")
    @ResponseWrapper(localName = "UploadBinaryByteArrayResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.UploadBinaryByteArrayResponse")
    public String uploadBinaryByteArray(
        @WebParam(name = "fileName", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String fileName,
        @WebParam(name = "data", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        byte[] data)
        throws IStreamUploadUploadBinaryByteArrayCoreServiceFaultFaultFaultMessage
    ;

}
