
package com.sdltridion.contentmanager.coreservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IStreamDownload", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sdltridion.contentmanager.r6.ObjectFactory.class,
    com.sdltridion.contentmanager.coreservice._2011.ObjectFactory.class,
    com.sdltridion.security.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface IStreamDownload {


    /**
     * 
     * @param itemId
     * @return
     *     returns byte[]
     * @throws IStreamDownloadDownloadBinaryContentCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadBinaryContent", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/IStreamDownload/DownloadBinaryContent")
    @WebResult(name = "DownloadBinaryContentResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "DownloadBinaryContent", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DownloadBinaryContent")
    @ResponseWrapper(localName = "DownloadBinaryContentResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DownloadBinaryContentResponse")
    public byte[] downloadBinaryContent(
        @WebParam(name = "itemId", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String itemId)
        throws IStreamDownloadDownloadBinaryContentCoreServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param path
     * @return
     *     returns byte[]
     * @throws IStreamDownloadDownloadRenderedBinaryCoreServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadRenderedBinary", action = "http://www.sdltridion.com/ContentManager/CoreService/2011/IStreamDownload/DownloadRenderedBinary")
    @WebResult(name = "DownloadRenderedBinaryResult", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
    @RequestWrapper(localName = "DownloadRenderedBinary", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DownloadRenderedBinary")
    @ResponseWrapper(localName = "DownloadRenderedBinaryResponse", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011", className = "com.sdltridion.contentmanager.coreservice._2011.DownloadRenderedBinaryResponse")
    public byte[] downloadRenderedBinary(
        @WebParam(name = "path", targetNamespace = "http://www.sdltridion.com/ContentManager/CoreService/2011")
        String path)
        throws IStreamDownloadDownloadRenderedBinaryCoreServiceFaultFaultFaultMessage
    ;

}
