<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="CoreService2011"
	targetNamespace="http://www.sdltridion.com/ContentManager/CoreService"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
	xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://www.sdltridion.com/ContentManager/CoreService"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
	xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
	xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:i0="http://www.sdltridion.com/ContentManager/CoreService/2011"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">

    <wsdl:import namespace="http://www.sdltridion.com/ContentManager/CoreService/2011" location="CoreService2011.wsdl0"/>
    <wsdl:types/>
    <wsdl:service name="CoreService2011">
        <wsdl:port name="basicHttp" binding="i0:basicHttp">
            <soap:address location="http://example.com/webservices/CoreService2011.svc/basicHttp"/>
        </wsdl:port>
        <wsdl:port name="streamDownload_basicHttp" binding="i0:streamDownload_basicHttp">
            <soap:address location="http://example.com/webservices/CoreService2011.svc/streamDownload_basicHttp"/>
        </wsdl:port>
        <wsdl:port name="streamUpload_basicHttp" binding="i0:streamUpload_basicHttp">
            <soap:address location="http://example.com/webservices/CoreService2011.svc/streamUpload_basicHttp"/>
        </wsdl:port>
        <wsdl:port name="wsHttp" binding="i0:wsHttp">
            <soap12:address location="http://example.com/webservices/CoreService2011.svc/wsHttp"/>
            <wsa10:EndpointReference>
                <wsa10:Address>http://example.com/webservices/CoreService2011.svc/wsHttp</wsa10:Address>
                <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
                    <Dns>localhost</Dns>
                </Identity>
            </wsa10:EndpointReference>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>